spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: library_user
    password: library_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # ??? validate, create-drop, none ? ??????????? ?? ?????? ????????????
    show-sql: true
  flyway:
    locations: classpath:db/migration
